### ISSUE TITLE
WDL failing at Plasmidfinder step

### ISSUE THREAD

**Issue by idolawoye** [Kincekara/C-BIRD#1]
Hi @Kincekara, 
I am launching the C-bird workflow on Terra and I have downloaded the databases as instructed in the documtation into my google bucket. When I run the workflow, it fails at plasmidfinder step with the following error:

`2022/10/24 23:39:51 Starting container setup.`
`2022/10/24 23:39:52 Done container setup.`
`2022/10/24 23:39:54 Starting localization.`
`2022/10/24 23:40:04 Localization script execution started...`
`2022/10/24 23:40:04 Localizing input gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/a72dd714-859e-4a39-8e69-0dd6385ef940/cbird_workflow/c8b9785b-ef78-446c-9312-8ea0057a05ac/call-plasmidfinder/script -> /cromwell_root/script`
`2022/10/24 23:40:06 Localizing input gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/a72dd714-859e-4a39-8e69-0dd6385ef940/cbird_workflow/c8b9785b-ef78-446c-9312-8ea0057a05ac/call-assembly/CCI10_scaffolds_trim.fasta -> /cromwell_root/fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/a72dd714-859e-4a39-8e69-0dd6385ef940/cbird_workflow/c8b9785b-ef78-446c-9312-8ea0057a05ac/call-assembly/CCI10_scaffolds_trim.fasta`
`2022/10/24 23:40:08 Localizing input gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/Databases/plasmidfinder-db.tar -> /cromwell_root/fc-1bde9971-12a8-416d-a2ff-e314c7ade234/Databases/plasmidfinder-db.tar`
`2022/10/24 23:40:09 Localization script execution complete.`
`2022/10/24 23:40:14 Done localization.`
`2022/10/24 23:40:15 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash quay.io/biocontainers/plasmidfinder@sha256:0b02ed6e441e055d3c6e6ed083ae8731430e009466aa82f8aad0484001ea41c3 /cromwell_root/script`
`plasmidfinder-db/`
`plasmidfinder-db/Rep_trans.fsa`
`plasmidfinder-db/Rep2.fsa`
`plasmidfinder-db/RepA_N.fsa`
`plasmidfinder-db/RepL.fsa`
`plasmidfinder-db/.gitignore`
`plasmidfinder-db/config`
`plasmidfinder-db/Rep3.fsa`
`plasmidfinder-db/enterobacteriales.fsa`
`plasmidfinder-db/Rep1.fsa`
`plasmidfinder-db/INSTALL.py`
`plasmidfinder-db/Inc18.fsa`
`plasmidfinder-db/NT_Rep.fsa`
`Input Error: The database config file could not be found!`
 `mv: can't rename 'results_tab.tsv': No such file or directory`

The config file is present in the plasmidfinder-db folder, so I'm not sure why it cannot be found

**Comment by Kincekara** [comment]
@idolawoye 
`2022/10/24 23:40:08 Localizing input gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/Databases/plasmidfinder-db.tar`
I think your plasmidfinder database is archived without compression. Can you try it again with gzip compression like **plasmidfinder-db.tar.gz**

**Comment by idolawoye** [comment]
@Kincekara I'm still having the same error even after compressing the archive

`Localizing input gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/Databases/plasmidfinder-db.tar.gz -> /cromwell_root/fc-1bde9971-12a8-416d-a2ff-e314c7ade234/Databases/plasmidfinder-db.tar.gz`

**Comment by Kincekara** [comment]
@idolawoye
My colleague reproduced this error by coincidence. The config file can be excluded while compressing. The following code should create a proper db.
```
git clone https://bitbucket.org/genomicepidemiology/plasmidfinder_db.git
cd plasmidfinder_db
tar -czvf plasmidfinder_db.tar.gz *
```

**Comment by idolawoye** [comment]
Thanks @Kincekara,
That resolved the issue. However, I had an error at "generate report" the final stage of the workflow:

`2022/10/25 17:59:50 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash kincekara/cbird-util@sha256:212495840fd797e59b7e31cd7f198c522ca122c27783eb2a354871db873fc030 /cromwell_root/script
Traceback (most recent call last):
File "/data/report_gen.py", line 204, in <module>
main()
File "/data/report_gen.py", line 57, in main
r_df = pd.read_csv(amr_report, sep = '\t')
File "/usr/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
return func(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
return _read(filepath_or_buffer, kwds)
File "/usr/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
parser = TextFileReader(filepath_or_buffer, **kwds)
File "/usr/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
self._engine = self._make_engine(self.engine)
File "/usr/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
return mapping[engine](self.f, **self.options) # type: ignore[call-arg]
File "/usr/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
self._reader = parsers.TextReader(self.handles.handle, **kwds)
File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
*pandas.errors.EmptyDataError: No columns to parse from file*
New version of client (14.1.1) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets`
`2022/10/25 17:59:56 Starting delocalization.`
`2022/10/25 17:59:57 Delocalization script execution started...`
`2022/10/25 17:59:57 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/9f0b45a5-400e-475b-8e0c-9079f6556839/cbird_workflow/424f28e9-910e-442b-a365-a76c95280b82/call-generate_report/memory_retry_rc`
`2022/10/25 18:00:00 Delocalizing output /cromwell_root/rc -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/9f0b45a5-400e-475b-8e0c-9079f6556839/cbird_workflow/424f28e9-910e-442b-a365-a76c95280b82/call-generate_report/rc`
`2022/10/25 18:00:01 Delocalizing output /cromwell_root/stdout -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/9f0b45a5-400e-475b-8e0c-9079f6556839/cbird_workflow/424f28e9-910e-442b-a365-a76c95280b82/call-generate_report/stdout`
`2022/10/25 18:00:03 Delocalizing output /cromwell_root/stderr -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/9f0b45a5-400e-475b-8e0c-9079f6556839/cbird_workflow/424f28e9-910e-442b-a365-a76c95280b82/call-generate_report/stderr`
`2022/10/25 18:00:04 Delocalizing output /cromwell_root/GENOME_RATIO -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/9f0b45a5-400e-475b-8e0c-9079f6556839/cbird_workflow/424f28e9-910e-442b-a365-a76c95280b82/call-generate_report/GENOME_RATIO`
`2022/10/25 18:00:06 Delocalizing output /cromwell_root/CCI15_QC_summary.html -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/9f0b45a5-400e-475b-8e0c-9079f6556839/cbird_workflow/424f28e9-910e-442b-a365-a76c95280b82/call-generate_report/CCI15_QC_summary.html`
`2022/10/25 18:00:08 Delocalizing output /cromwell_root/CCI15_txt_report.txt -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/9f0b45a5-400e-475b-8e0c-9079f6556839/cbird_workflow/424f28e9-910e-442b-a365-a76c95280b82/call-generate_report/CCI15_txt_report.txt
Required file output '/cromwell_root/CCI15_txt_report.txt' does not exist.`

**Comment by idolawoye** [comment]
@Kincekara also I noticed that none of the assemblies produced AMR results. Which I'm guessing is affecting the report generation

**Comment by idolawoye** [comment]
This is the log file of the AMR step:

2022/10/25 22:28:03 Starting container setup.
2022/10/25 22:28:05 Done container setup.
2022/10/25 22:28:07 Starting localization.
2022/10/25 22:28:16 Localization script execution started...
2022/10/25 22:28:16 Localizing input gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/Databases/amrfinderplus_db_3.10.tar.gz -> /cromwell_root/fc-1bde9971-12a8-416d-a2ff-e314c7ade234/Databases/amrfinderplus_db_3.10.tar.gz
2022/10/25 22:28:19 Localizing input gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-assembly/cacheCopy/CCI1_scaffolds_trim.fasta -> /cromwell_root/fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-assembly/cacheCopy/CCI1_scaffolds_trim.fasta
2022/10/25 22:28:21 Localizing input gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/script -> /cromwell_root/script
2022/10/25 22:28:22 Localization script execution complete.
2022/10/25 22:28:27 Done localization.
2022/10/25 22:28:28 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash kincekara/amrfinder@sha256:eac36acfa1196124cf392dd6dfd71dcecace0b54713d799849ec34693e223301 /cromwell_root/script
Tue Oct 25 22:28:29 UTC 2022
3.10.40
allele_counts_by_year/
allele_counts_by_year/index.html
allele_counts_by_year/mcr.tsv
allele_counts_by_year/qnr.tsv
allele_counts_by_year/bla.tsv
AMR_CDS
AMR_DNA-Campylobacter
AMR_DNA-Campylobacter.tab
AMR_DNA-Clostridioides_difficile
AMR_DNA-Clostridioides_difficile.tab
AMR_DNA-Enterococcus_faecalis
AMR_DNA-Enterococcus_faecalis.tab
AMR_DNA-Enterococcus_faecium
AMR_DNA-Enterococcus_faecium.tab
AMR_DNA-Escherichia
AMR_DNA-Escherichia.tab
AMR_DNA-Neisseria
AMR_DNA-Neisseria.tab
AMR_DNA-Salmonella
AMR_DNA-Salmonella.tab
AMR_DNA-Staphylococcus_aureus
AMR_DNA-Staphylococcus_aureus.tab
AMR_DNA-Streptococcus_pneumoniae
AMR_DNA-Streptococcus_pneumoniae.tab
AMR.LIB
AMRProt
AMRProt-mutation.tab
AMRProt-suppress
AMRProt-susceptible.tab
amr_targets.fa
changelog.txt
changes.txt
database_format_version.txt
fam.tab
index.html
ReferenceGeneCatalog.txt
ReferenceGeneHierarchy.txt
taxgroup.tab
version.txt
amrfinder_organism is set to: Klebsiella
Running: amrfinder --plus -d ./db/ --organism Klebsiella --name CCI1 --nucleotide /cromwell_root/fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-assembly/cacheCopy/CCI1_scaffolds_trim.fasta -o CCI1_amrfinder_all.tsv --threads 4
Software directory: '/amrfinder/'
Software version: 3.10.40
Database directory: '/cromwell_root/db'

[1;31m*** ERROR ***[0m
The BLAST database for AMRProt was not found. Use amrfinder -u to download and prepare database for AMRFinderPlus

HOSTNAME: a2c4e7d8ac6b
SHELL: ?
PWD: /cromwell_root
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/amrfinder
Progam name:  amrfinder
Command line: amrfinder --plus -d ./db/ --organism Klebsiella --name CCI1 --nucleotide /cromwell_root/fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-assembly/cacheCopy/CCI1_scaffolds_trim.fasta -o CCI1_amrfinder_all.tsv --threads 4
2022/10/25 22:28:31 Starting delocalization.
2022/10/25 22:28:32 Delocalization script execution started...
2022/10/25 22:28:32 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/memory_retry_rc
2022/10/25 22:28:35 Delocalizing output /cromwell_root/rc -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/rc
2022/10/25 22:28:36 Delocalizing output /cromwell_root/stdout -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/stdout
2022/10/25 22:28:38 Delocalizing output /cromwell_root/stderr -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/stderr
2022/10/25 22:28:39 Delocalizing output /cromwell_root/CCI1_amrfinder_all.tsv -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/CCI1_amrfinder_all.tsv
2022/10/25 22:28:41 Delocalizing output /cromwell_root/AMRFINDER_VERSION -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/AMRFINDER_VERSION
2022/10/25 22:28:42 Delocalizing output /cromwell_root/AMRFINDER_DB_VERSION -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/AMRFINDER_DB_VERSION
2022/10/25 22:28:44 Delocalizing output /cromwell_root/STRESS_GENES -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/STRESS_GENES
2022/10/25 22:28:45 Delocalizing output /cromwell_root/CCI1_amrfinder_virulence.tsv -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/CCI1_amrfinder_virulence.tsv
2022/10/25 22:28:47 Delocalizing output /cromwell_root/CCI1_amrfinder_amr.tsv -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/CCI1_amrfinder_amr.tsv
2022/10/25 22:28:48 Delocalizing output /cromwell_root/AMR_GENES -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/AMR_GENES
2022/10/25 22:28:50 Delocalizing output /cromwell_root/CCI1_amrfinder_stress.tsv -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/CCI1_amrfinder_stress.tsv
2022/10/25 22:28:51 Delocalizing output /cromwell_root/VIRULENCE_GENES -> gs://fc-1bde9971-12a8-416d-a2ff-e314c7ade234/submissions/847591f5-a479-4106-b87f-751a7cc822f3/cbird_workflow/27697c04-4bff-409d-876d-ad7d06b461e9/call-amr/VIRULENCE_GENES
2022/10/25 22:28:53 Delocalization script execution complete.
2022/10/25 22:28:54 Done delocalization.

**Comment by idolawoye** [comment]
Hi @Kincekara, I was able to fix the issue with the AMR db. It was failing because I was using the db I curled from NCBI directly. In order to make it work, I updated it using the amrfinder software on my PC and compressed the db before using it on Terra.
Thanks a lot!
